In [1]:
import pandas as pd

In [3]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Adding a new column

### 1.1 Adding a new column with a scalar value

In [5]:
# adding new column
df_exams['language score'] = 70
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70

### 1.2 Adding a new column with an array

the dataframe has 1000 rows, which is why we need to create an array with 1000 elements

In [6]:
# import numpy
import numpy as np

In [9]:
# array of 1000 elements 
language_score = np.arange(0, 1000)

In [10]:
len(language_score)

1000

In [12]:
# adding new column using the array
df_exams['language score'] = language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4

In [15]:
# create random integer numbers between 1 to 100
int_language_score = np.random.randint(1, 100, size = 1000)

In [16]:
len(int_language_score)

1000

In [18]:
# min value = inclusive and high value = exclusive
min(int_language_score)
max(int_language_score)

np.int32(99)

In [19]:
# adding the new column using array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,33
1,female,group C,some college,standard,completed,69,90,88,14
2,female,group B,master's degree,standard,none,90,95,93,98
3,male,group A,associate's degree,free/reduced,none,47,57,44,59
4,male,group C,some college,standard,none,76,78,75,63
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,50
996,male,group C,high school,free/reduced,none,62,55,55,98
997,female,group C,high school,free/reduced,completed,59,71,65,74
998,female,group D,some college,standard,completed,68,78,77,7
999,female,group D,some college,free/reduced,none,77,86,86,27

In [21]:
# random float number between 1 to 100 
np.random.uniform(1, 100, size = 100)

array([64.70808474, 69.17297404, 46.15627076, 70.96818824,  1.01790142,
       33.93577059, 58.74623226, 36.87115521, 34.95610538, 63.87980597,
       30.23615338, 30.84415875, 95.33125503, 10.5416094 , 15.52447569,
       39.62199653, 39.6130637 , 46.27564038, 85.82518288, 62.93404868,
       68.03255025, 83.23512781, 89.0525759 , 32.28024022, 69.07077945,
       69.07115507, 15.9892438 , 59.84094926, 97.16630341, 37.31739859,
        4.71388207, 49.9984403 , 86.71300156, 69.24162836, 49.94937574,
       67.25429591, 35.27719546, 63.86365342,  9.86006858, 33.01277413,
       93.57619908, 90.55897121,  2.50232009, 21.44883977, 78.40776468,
       46.19001776, 62.51436092, 13.9875658 , 16.82347842, 98.2376549 ,
       94.07541932,  5.26511036, 29.5317378 , 12.80521839, 83.63500539,
       36.09410652, 68.20464523, 43.93997046, 60.26539338, 38.00973028,
       72.75534253, 63.46983653, 40.80976519, 78.95230812, 98.24686199,
       97.97575438, 15.90270298,  1.99390631, 77.18835783, 63.70065559,
       54.45906124, 70.44264286, 16.7520778 , 99.30399242, 11.91365761,
       39.89022243, 46.44887739, 65.8899791 , 92.73131723, 53.59533183,
       81.38720577,  7.56579157, 25.38154922, 76.3669345 , 14.1486659 ,
       15.06481945,  8.96248283, 20.47890006, 81.35691162, 54.59708848,
       32.76510627, 27.04370724, 38.38459074, 74.02932135, 40.5671239 ,
       84.68349319, 25.0721666 , 31.20860989, 99.6070122 , 95.11200008])