In [1]:
import pandas as pd
import numpy as np

# 1. Creating a dataframe using array

### 1.1 Option-1

In [5]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [9]:
# creating a dataframe 
df = pd.DataFrame(data, 
             index=['row1', 'row2', 'row3'], 
             columns=['col1', 'col2']
            )

In [10]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### 1.2 Option-2

In [12]:
# creating an array with list shape 
data = ([[1,4], [2,5], [3,6]])

In [13]:
# creating a dataframe 
df = pd.DataFrame(data, 
             index=['row1', 'row2', 'row3'], 
             columns=['col1', 'col2']
            )

In [15]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# 2. Creating a DataFrame from dictinary

In [17]:
# lists used for this one
states = ['California', 'Texas', 'New York', 'Florida', 'Illinois']
population = [22.2, 29.0, 19.8, 21.5, 12.7]

In [20]:
# storing lists in the dictionary
dict_states = {'States':states,
               'Population':population
               }

In [23]:
# creating the dataframe from the dictionary
df_population = pd.DataFrame(dict_states)

In [24]:
df_population

       States  Population
0  California        22.2
1       Texas        29.0
2    New York        19.8
3     Florida        21.5
4    Illinois        12.7

# 3. Creating a DataFrame from a csv file

In [25]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [31]:
# show the first 5 rows of the dataframe
df_exams.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75